[versions]
agp = "8.2.2"
androidx-test-core = "1.6.0"
androidx-test-junit = "1.2.0"
androidx-test-runner = "1.6.0"
ben-manes-versions = "0.51.0"
firebase-bom = "33.1.1"
gitlive-firebase-java-sdk = "0.4.3"
gson = "2.11.0"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinx-coroutines = "1.9.0-RC"
kotlinx-serialization = "1.7.0"
kotlinx-binarycompatibilityvalidator = "0.15.0-Beta.2"
kotlinter = "4.4.0"
settings-api = "2.0"
settings-language = "2.0"
firebase-cocoapods = "10.28.0"
test-logger-plugin = "3.2.0"
dokka = "1.9.20"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
gitlive-firebase-java-sdk = { module = "dev.gitlive:firebase-java-sdk", version.ref = "gitlive-firebase-java-sdk" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics"}
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx"}
google-firebase-common-ktx = { module = "com.google.firebase:firebase-common-ktx"}
google-firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx"}
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx"}
google-firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx"}
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore"}
google-firebase-functions = { module = "com.google.firebase:firebase-functions"}
google-firebase-installations-ktx = { module = "com.google.firebase:firebase-installations-ktx"}
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging"}
google-firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx"}
google-firebase-storage = { module = "com.google.firebase:firebase-storage"}
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-binarycompatibilityvalidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binarycompatibilityvalidator" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
test-logger-plugin = { id = "com.adarshr.test-logger", version.ref = "test-logger-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
