# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  release:
    types: [ prereleased, released ]

env:
  sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
  sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Setup versions
        run: ./gradlew :updateVersions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish Firebase App
        run: ./gradlew :firebase-app:publish
      - name: Publish Firebase Auth
        run: ./gradlew :firebase-auth:publish
      - name: Publish Firebase Common
        run: ./gradlew :firebase-common:publish
      - name: Publish Firebase Config
        run: ./gradlew :firebase-config:publish
      - name: Publish Firebase Database
        run: ./gradlew :firebase-database:publish
      - name: Publish Firebase Firestore
        run: ./gradlew :firebase-firestore:publish
      - name: Publish Firebase Functions
        run: ./gradlew :firebase-functions:publish
      - name: Publish Firebase Storage
        run: ./gradlew :firebase-storage:publish
      - name: Publish Firebase Installations
        run: ./gradlew :firebase-installations:publish
      - name: Publish Firebase Performance
        run: ./gradlew :firebase-perf:publish
      - name: Publish Firebase Crashlytics
        run: ./gradlew :firebase-crashlytics:publish